version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: force_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: mysql:8
        restart: always
        container_name: force_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

    nginx:
        image: nginx:stable
        container_name: force_nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    dbdata:
